-- ============================================================
-- NeuroLearn: Student Profiles Table
-- Run this once in pgAdmin:
--   1. Open pgAdmin → your server → your database
--   2. Right-click database → Query Tool
--   3. Paste this SQL and click Run (▶)
-- ============================================================

-- Create the table if it doesn't already exist
CREATE TABLE IF NOT EXISTS student_profiles (
  -- Unique ID generated by the app (UUID)
  id              UUID          PRIMARY KEY,

  -- Collected during "Get Started" onboarding
  name            TEXT          NOT NULL DEFAULT 'Learner',
  age_group       TEXT          NOT NULL DEFAULT 'teen',
  grade_level     INT           NOT NULL DEFAULT 10,

  -- Condition the student selects (dyslexia / adhd / both / unsure)
  diagnosis_type  TEXT[]        NOT NULL DEFAULT '{}',
  medication_status BOOLEAN     NOT NULL DEFAULT FALSE,
  comfort_level   INT           NOT NULL DEFAULT 7,

  -- AI-computed learning weights
  dyslexia_score  DECIMAL(5,2)  NOT NULL DEFAULT 20,
  adhd_score      DECIMAL(5,2)  NOT NULL DEFAULT 20,
  standard_score  DECIMAL(5,2)  NOT NULL DEFAULT 60,
  preferred_mode  TEXT          NOT NULL DEFAULT 'standard',

  -- Reading behaviour
  reading_speed   TEXT          NOT NULL DEFAULT 'normal',
  focus_span      TEXT          NOT NULL DEFAULT 'medium',

  -- Display preferences
  color_preference TEXT         NOT NULL DEFAULT 'dark',
  font_scale      DECIMAL(4,2)  NOT NULL DEFAULT 1.0,
  word_spacing    DECIMAL(4,2)  NOT NULL DEFAULT 1.0,

  -- Timestamps
  created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

-- Auto-update updated_at on every change
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_updated_at ON student_profiles;
CREATE TRIGGER trg_updated_at
  BEFORE UPDATE ON student_profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
